export const OPEN_PHOTO_DETAILS_MODAL = 'OPEN_PHOTO_DETAILS_MODAL';
export const CLOSE_PHOTO_DETAILS_MODAL = 'CLOSE_PHOTO_DETAILS_MODAL';
export const OPEN_FAVORITES_MODAL = 'OPEN_FAVORITES_MODAL';
export const CLOSE_FAVORITES_MODAL = 'CLOSE_FAVORITES_MODAL';